version: '3.4'

services:
  shoppingcart:
    ports:
      - "8099:80"
    image: ${DOCKER_REGISTRY-}shoppingcart
    build:
      context: .
      dockerfile: ShoppingCart/Dockerfile
    depends_on:
      - db
    links:
      - seq 
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8098:80" # UI
      - "5341:5341" # Ingest
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
       SA_PASSWORD: "1Secure*Password1#"
       ACCEPT_EULA: "Y"