version: '3.4'

services:
  shoppingcart:
    ports:
      - "8099:80"
    image: ${DOCKER_REGISTRY-}shoppingcart
    build:
      context: .
      dockerfile: ShoppingCart/Dockerfile
    depends_on:
      - db
  seq.logging:
    image: datalust/seq
    container_name: seq.logging
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80" # UI
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
       SA_PASSWORD: "1Secure*Password1#"
       ACCEPT_EULA: "Y"

  #dockersqlserver:
  #  image: ${DOCKER_REGISTRY-}dockersqlserver
  #  build:
  #    context: .
  #    dockerfile: DockerSqlServer/Dockerfile
  #  depends_on:
  #    - db